# Generated by Django 3.1.7 on 2021-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210312_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
