# Generated by Django 3.1.7 on 2021-03-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20210312_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
    ]
